### ISSUE TITLE
Knowing when the font is constructed

### ISSUE THREAD

**Issue by YoruNoHikage** [byte-foundry/prototypo-library#3]
For the extension, I build the font and then transmit the source from an iframe to the background script. But since we don't have any Promise returned to know when the font has been build, I have only the previous version.

I would say that https://github.com/byte-foundry/prototypo-library/blob/master/src/index.js#L135 and https://github.com/byte-foundry/prototypo-library/blob/master/src/index.js#L114 could returned `createFont` that would returned a Promise resolved when the font is constructed.

**Comment by FranzPoize** [comment]
Yes, can you do it? I don't see a problem returning createFont and that createFont returns a Promise.

**Comment by YoruNoHikage** [comment]
Done! See #4
